# Generated by Django 2.1.1 on 2018-11-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokyo_in_map', '0003_auto_20181115_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='Spot',
        ),
    ]
