# Generated by Django 2.1.1 on 2018-11-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokyo_in_map', '0004_auto_20181119_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='content',
        ),
        migrations.AddField(
            model_name='spot',
            name='content_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
