# Generated by Django 2.1.1 on 2018-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokyo_in_map', '0007_spot_intensity_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='intensity_meter',
            field=models.IntegerField(default=50),
        ),
    ]
