# Generated by Django 2.1.5 on 2019-01-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokyo_in_map', '0009_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='content_url',
        ),
    ]
